// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpcmodules

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NumberRpcClient is the client API for NumberRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NumberRpcClient interface {
	// api
	AddNumber(ctx context.Context, in *Number, opts ...grpc.CallOption) (*ResponseStatus, error)
	RemoveNumber(ctx context.Context, in *Number, opts ...grpc.CallOption) (*ResponseStatus, error)
	QueryNumber(ctx context.Context, in *Number, opts ...grpc.CallOption) (*QueryResponse, error)
	// guesser
	IsNumberExist(ctx context.Context, opts ...grpc.CallOption) (NumberRpc_IsNumberExistClient, error)
}

type numberRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewNumberRpcClient(cc grpc.ClientConnInterface) NumberRpcClient {
	return &numberRpcClient{cc}
}

func (c *numberRpcClient) AddNumber(ctx context.Context, in *Number, opts ...grpc.CallOption) (*ResponseStatus, error) {
	out := new(ResponseStatus)
	err := c.cc.Invoke(ctx, "/numberModel.NumberRpc/AddNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *numberRpcClient) RemoveNumber(ctx context.Context, in *Number, opts ...grpc.CallOption) (*ResponseStatus, error) {
	out := new(ResponseStatus)
	err := c.cc.Invoke(ctx, "/numberModel.NumberRpc/RemoveNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *numberRpcClient) QueryNumber(ctx context.Context, in *Number, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, "/numberModel.NumberRpc/QueryNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *numberRpcClient) IsNumberExist(ctx context.Context, opts ...grpc.CallOption) (NumberRpc_IsNumberExistClient, error) {
	stream, err := c.cc.NewStream(ctx, &NumberRpc_ServiceDesc.Streams[0], "/numberModel.NumberRpc/IsNumberExist", opts...)
	if err != nil {
		return nil, err
	}
	x := &numberRpcIsNumberExistClient{stream}
	return x, nil
}

type NumberRpc_IsNumberExistClient interface {
	Send(*GuessNumber) error
	Recv() (*NumberExistResponse, error)
	grpc.ClientStream
}

type numberRpcIsNumberExistClient struct {
	grpc.ClientStream
}

func (x *numberRpcIsNumberExistClient) Send(m *GuessNumber) error {
	return x.ClientStream.SendMsg(m)
}

func (x *numberRpcIsNumberExistClient) Recv() (*NumberExistResponse, error) {
	m := new(NumberExistResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NumberRpcServer is the server API for NumberRpc service.
// All implementations must embed UnimplementedNumberRpcServer
// for forward compatibility
type NumberRpcServer interface {
	// api
	AddNumber(context.Context, *Number) (*ResponseStatus, error)
	RemoveNumber(context.Context, *Number) (*ResponseStatus, error)
	QueryNumber(context.Context, *Number) (*QueryResponse, error)
	// guesser
	IsNumberExist(NumberRpc_IsNumberExistServer) error
	mustEmbedUnimplementedNumberRpcServer()
}

// UnimplementedNumberRpcServer must be embedded to have forward compatible implementations.
type UnimplementedNumberRpcServer struct {
}

func (UnimplementedNumberRpcServer) AddNumber(context.Context, *Number) (*ResponseStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNumber not implemented")
}
func (UnimplementedNumberRpcServer) RemoveNumber(context.Context, *Number) (*ResponseStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveNumber not implemented")
}
func (UnimplementedNumberRpcServer) QueryNumber(context.Context, *Number) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryNumber not implemented")
}
func (UnimplementedNumberRpcServer) IsNumberExist(NumberRpc_IsNumberExistServer) error {
	return status.Errorf(codes.Unimplemented, "method IsNumberExist not implemented")
}
func (UnimplementedNumberRpcServer) mustEmbedUnimplementedNumberRpcServer() {}

// UnsafeNumberRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NumberRpcServer will
// result in compilation errors.
type UnsafeNumberRpcServer interface {
	mustEmbedUnimplementedNumberRpcServer()
}

func RegisterNumberRpcServer(s grpc.ServiceRegistrar, srv NumberRpcServer) {
	s.RegisterService(&NumberRpc_ServiceDesc, srv)
}

func _NumberRpc_AddNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Number)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NumberRpcServer).AddNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/numberModel.NumberRpc/AddNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NumberRpcServer).AddNumber(ctx, req.(*Number))
	}
	return interceptor(ctx, in, info, handler)
}

func _NumberRpc_RemoveNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Number)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NumberRpcServer).RemoveNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/numberModel.NumberRpc/RemoveNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NumberRpcServer).RemoveNumber(ctx, req.(*Number))
	}
	return interceptor(ctx, in, info, handler)
}

func _NumberRpc_QueryNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Number)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NumberRpcServer).QueryNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/numberModel.NumberRpc/QueryNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NumberRpcServer).QueryNumber(ctx, req.(*Number))
	}
	return interceptor(ctx, in, info, handler)
}

func _NumberRpc_IsNumberExist_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NumberRpcServer).IsNumberExist(&numberRpcIsNumberExistServer{stream})
}

type NumberRpc_IsNumberExistServer interface {
	Send(*NumberExistResponse) error
	Recv() (*GuessNumber, error)
	grpc.ServerStream
}

type numberRpcIsNumberExistServer struct {
	grpc.ServerStream
}

func (x *numberRpcIsNumberExistServer) Send(m *NumberExistResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *numberRpcIsNumberExistServer) Recv() (*GuessNumber, error) {
	m := new(GuessNumber)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NumberRpc_ServiceDesc is the grpc.ServiceDesc for NumberRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NumberRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "numberModel.NumberRpc",
	HandlerType: (*NumberRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddNumber",
			Handler:    _NumberRpc_AddNumber_Handler,
		},
		{
			MethodName: "RemoveNumber",
			Handler:    _NumberRpc_RemoveNumber_Handler,
		},
		{
			MethodName: "QueryNumber",
			Handler:    _NumberRpc_QueryNumber_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "IsNumberExist",
			Handler:       _NumberRpc_IsNumberExist_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "onboarding.com/number/grpcmodules/number.proto",
}
