// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: onboarding.com/number/grpcmodules/number.proto

package grpcmodules

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Number struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num uint32 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *Number) Reset() {
	*x = Number{}
	if protoimpl.UnsafeEnabled {
		mi := &file_onboarding_com_number_grpcmodules_number_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Number) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Number) ProtoMessage() {}

func (x *Number) ProtoReflect() protoreflect.Message {
	mi := &file_onboarding_com_number_grpcmodules_number_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Number.ProtoReflect.Descriptor instead.
func (*Number) Descriptor() ([]byte, []int) {
	return file_onboarding_com_number_grpcmodules_number_proto_rawDescGZIP(), []int{0}
}

func (x *Number) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type GuessNumber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num uint32 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Id  uint32 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GuessNumber) Reset() {
	*x = GuessNumber{}
	if protoimpl.UnsafeEnabled {
		mi := &file_onboarding_com_number_grpcmodules_number_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuessNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuessNumber) ProtoMessage() {}

func (x *GuessNumber) ProtoReflect() protoreflect.Message {
	mi := &file_onboarding_com_number_grpcmodules_number_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuessNumber.ProtoReflect.Descriptor instead.
func (*GuessNumber) Descriptor() ([]byte, []int) {
	return file_onboarding_com_number_grpcmodules_number_proto_rawDescGZIP(), []int{1}
}

func (x *GuessNumber) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *GuessNumber) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type NumberInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num      *Number               `protobuf:"bytes,1,opt,name=num,proto3" json:"num,omitempty"`
	IsActive bool                  `protobuf:"varint,2,opt,name=isActive,proto3" json:"isActive,omitempty"`
	Guesses  []*NumberInfo_Guesses `protobuf:"bytes,3,rep,name=guesses,proto3" json:"guesses,omitempty"`
}

func (x *NumberInfo) Reset() {
	*x = NumberInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_onboarding_com_number_grpcmodules_number_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumberInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberInfo) ProtoMessage() {}

func (x *NumberInfo) ProtoReflect() protoreflect.Message {
	mi := &file_onboarding_com_number_grpcmodules_number_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberInfo.ProtoReflect.Descriptor instead.
func (*NumberInfo) Descriptor() ([]byte, []int) {
	return file_onboarding_com_number_grpcmodules_number_proto_rawDescGZIP(), []int{2}
}

func (x *NumberInfo) GetNum() *Number {
	if x != nil {
		return x.Num
	}
	return nil
}

func (x *NumberInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *NumberInfo) GetGuesses() []*NumberInfo_Guesses {
	if x != nil {
		return x.Guesses
	}
	return nil
}

type ResponseStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok      bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrCode uint32 `protobuf:"varint,2,opt,name=errCode,proto3" json:"errCode,omitempty"`
}

func (x *ResponseStatus) Reset() {
	*x = ResponseStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_onboarding_com_number_grpcmodules_number_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseStatus) ProtoMessage() {}

func (x *ResponseStatus) ProtoReflect() protoreflect.Message {
	mi := &file_onboarding_com_number_grpcmodules_number_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseStatus.ProtoReflect.Descriptor instead.
func (*ResponseStatus) Descriptor() ([]byte, []int) {
	return file_onboarding_com_number_grpcmodules_number_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseStatus) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ResponseStatus) GetErrCode() uint32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

type QueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Info   *NumberInfo     `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_onboarding_com_number_grpcmodules_number_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onboarding_com_number_grpcmodules_number_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_onboarding_com_number_grpcmodules_number_proto_rawDescGZIP(), []int{4}
}

func (x *QueryResponse) GetStatus() *ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *QueryResponse) GetInfo() *NumberInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type NumberExistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Exist  bool            `protobuf:"varint,2,opt,name=exist,proto3" json:"exist,omitempty"`
}

func (x *NumberExistResponse) Reset() {
	*x = NumberExistResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_onboarding_com_number_grpcmodules_number_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumberExistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberExistResponse) ProtoMessage() {}

func (x *NumberExistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onboarding_com_number_grpcmodules_number_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberExistResponse.ProtoReflect.Descriptor instead.
func (*NumberExistResponse) Descriptor() ([]byte, []int) {
	return file_onboarding_com_number_grpcmodules_number_proto_rawDescGZIP(), []int{5}
}

func (x *NumberExistResponse) GetStatus() *ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *NumberExistResponse) GetExist() bool {
	if x != nil {
		return x.Exist
	}
	return false
}

type NumberInfo_Guesses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuesserID string                 `protobuf:"bytes,1,opt,name=guesserID,proto3" json:"guesserID,omitempty"`
	Found     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=found,proto3" json:"found,omitempty"`
}

func (x *NumberInfo_Guesses) Reset() {
	*x = NumberInfo_Guesses{}
	if protoimpl.UnsafeEnabled {
		mi := &file_onboarding_com_number_grpcmodules_number_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumberInfo_Guesses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberInfo_Guesses) ProtoMessage() {}

func (x *NumberInfo_Guesses) ProtoReflect() protoreflect.Message {
	mi := &file_onboarding_com_number_grpcmodules_number_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberInfo_Guesses.ProtoReflect.Descriptor instead.
func (*NumberInfo_Guesses) Descriptor() ([]byte, []int) {
	return file_onboarding_com_number_grpcmodules_number_proto_rawDescGZIP(), []int{2, 0}
}

func (x *NumberInfo_Guesses) GetGuesserID() string {
	if x != nil {
		return x.GuesserID
	}
	return ""
}

func (x *NumberInfo_Guesses) GetFound() *timestamppb.Timestamp {
	if x != nil {
		return x.Found
	}
	return nil
}

var File_onboarding_com_number_grpcmodules_number_proto protoreflect.FileDescriptor

var file_onboarding_com_number_grpcmodules_number_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x6d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x73, 0x2f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0b, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1a,
	0x0a, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x2f, 0x0a, 0x0b, 0x47, 0x75,
	0x65, 0x73, 0x73, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0xe5, 0x01, 0x0a, 0x0a,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x25, 0x0a, 0x03, 0x6e, 0x75,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x03, 0x6e, 0x75,
	0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x39, 0x0a,
	0x07, 0x67, 0x75, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x47, 0x75, 0x65, 0x73, 0x73, 0x65, 0x73, 0x52,
	0x07, 0x67, 0x75, 0x65, 0x73, 0x73, 0x65, 0x73, 0x1a, 0x59, 0x0a, 0x07, 0x47, 0x75, 0x65, 0x73,
	0x73, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x75, 0x65, 0x73, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x75, 0x65, 0x73, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x30, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x05, 0x66, 0x6f,
	0x75, 0x6e, 0x64, 0x22, 0x3a, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x22,
	0x71, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2b, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e,
	0x66, 0x6f, 0x22, 0x60, 0x0a, 0x13, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x45, 0x78, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x78, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65,
	0x78, 0x69, 0x73, 0x74, 0x32, 0xa5, 0x02, 0x0a, 0x09, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52,
	0x70, 0x63, 0x12, 0x3f, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x13, 0x2e, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x1a, 0x1b, 0x2e, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0c, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x1a, 0x1b, 0x2e, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0b, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x1a, 0x1a, 0x2e, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x0d, 0x49, 0x73, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x45, 0x78, 0x69, 0x73, 0x74, 0x12, 0x18, 0x2e, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x47, 0x75, 0x65, 0x73, 0x73, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x1a, 0x20, 0x2e, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x45, 0x78, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x23, 0x5a, 0x21,
	0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_onboarding_com_number_grpcmodules_number_proto_rawDescOnce sync.Once
	file_onboarding_com_number_grpcmodules_number_proto_rawDescData = file_onboarding_com_number_grpcmodules_number_proto_rawDesc
)

func file_onboarding_com_number_grpcmodules_number_proto_rawDescGZIP() []byte {
	file_onboarding_com_number_grpcmodules_number_proto_rawDescOnce.Do(func() {
		file_onboarding_com_number_grpcmodules_number_proto_rawDescData = protoimpl.X.CompressGZIP(file_onboarding_com_number_grpcmodules_number_proto_rawDescData)
	})
	return file_onboarding_com_number_grpcmodules_number_proto_rawDescData
}

var file_onboarding_com_number_grpcmodules_number_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_onboarding_com_number_grpcmodules_number_proto_goTypes = []interface{}{
	(*Number)(nil),                // 0: numberModel.Number
	(*GuessNumber)(nil),           // 1: numberModel.GuessNumber
	(*NumberInfo)(nil),            // 2: numberModel.NumberInfo
	(*ResponseStatus)(nil),        // 3: numberModel.ResponseStatus
	(*QueryResponse)(nil),         // 4: numberModel.QueryResponse
	(*NumberExistResponse)(nil),   // 5: numberModel.NumberExistResponse
	(*NumberInfo_Guesses)(nil),    // 6: numberModel.NumberInfo.Guesses
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_onboarding_com_number_grpcmodules_number_proto_depIdxs = []int32{
	0,  // 0: numberModel.NumberInfo.num:type_name -> numberModel.Number
	6,  // 1: numberModel.NumberInfo.guesses:type_name -> numberModel.NumberInfo.Guesses
	3,  // 2: numberModel.QueryResponse.status:type_name -> numberModel.ResponseStatus
	2,  // 3: numberModel.QueryResponse.info:type_name -> numberModel.NumberInfo
	3,  // 4: numberModel.NumberExistResponse.status:type_name -> numberModel.ResponseStatus
	7,  // 5: numberModel.NumberInfo.Guesses.found:type_name -> google.protobuf.Timestamp
	0,  // 6: numberModel.NumberRpc.AddNumber:input_type -> numberModel.Number
	0,  // 7: numberModel.NumberRpc.RemoveNumber:input_type -> numberModel.Number
	0,  // 8: numberModel.NumberRpc.QueryNumber:input_type -> numberModel.Number
	1,  // 9: numberModel.NumberRpc.IsNumberExist:input_type -> numberModel.GuessNumber
	3,  // 10: numberModel.NumberRpc.AddNumber:output_type -> numberModel.ResponseStatus
	3,  // 11: numberModel.NumberRpc.RemoveNumber:output_type -> numberModel.ResponseStatus
	4,  // 12: numberModel.NumberRpc.QueryNumber:output_type -> numberModel.QueryResponse
	5,  // 13: numberModel.NumberRpc.IsNumberExist:output_type -> numberModel.NumberExistResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_onboarding_com_number_grpcmodules_number_proto_init() }
func file_onboarding_com_number_grpcmodules_number_proto_init() {
	if File_onboarding_com_number_grpcmodules_number_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_onboarding_com_number_grpcmodules_number_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Number); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_onboarding_com_number_grpcmodules_number_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuessNumber); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_onboarding_com_number_grpcmodules_number_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumberInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_onboarding_com_number_grpcmodules_number_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_onboarding_com_number_grpcmodules_number_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_onboarding_com_number_grpcmodules_number_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumberExistResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_onboarding_com_number_grpcmodules_number_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumberInfo_Guesses); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_onboarding_com_number_grpcmodules_number_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_onboarding_com_number_grpcmodules_number_proto_goTypes,
		DependencyIndexes: file_onboarding_com_number_grpcmodules_number_proto_depIdxs,
		MessageInfos:      file_onboarding_com_number_grpcmodules_number_proto_msgTypes,
	}.Build()
	File_onboarding_com_number_grpcmodules_number_proto = out.File
	file_onboarding_com_number_grpcmodules_number_proto_rawDesc = nil
	file_onboarding_com_number_grpcmodules_number_proto_goTypes = nil
	file_onboarding_com_number_grpcmodules_number_proto_depIdxs = nil
}
